### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by BorisTherin** [3forges/juste-un-curieux#41]
pnpm run build
=>
> justincurieux@0.0.1 build /home/bob/just1/juste-un-curieux
> npm run "meta:build" && astro build

> justincurieux@0.0.1 meta:build
> tsc -p ./.ci/tsconfig.json

06:51:25 PM [content] Types generated 727ms
06:51:25 PM [build] output target: static
06:51:25 PM [build] Collecting build info...
06:51:25 PM [build] Completed in 2.32s.
06:51:25 PM [build] Building static entrypoints...
[commonjs--resolver] Unexpected token (116:8) in /home/bob/just1/juste-un-curieux/node_modules/.pnpm/astro@2.10.15_sharp@0.32.5/node_modules/astro/dist/core/create-vite.js
file: /home/bob/just1/juste-un-curieux/node_modules/.pnpm/astro@2.10.15_sharp@0.32.5/node_modules/astro/dist/core/create-vite.js:116:8
114:     envPrefix: ((_a = settings.config.vite) == null ? void 0 : _a.envPrefix) ?? "PUBLIC_",
115:     define: {
116:       ""https://astro-moon-landing.netlify.app/"": settings.config.site ? JSON.stringify(settings.config.site) : "und...
             ^
117:     },
118:     server: {
 error   Unexpected token (116:8) in /home/bob/just1/juste-un-curieux/node_modules/.pnpm/astro@2.10.15_sharp@0.32.5/node_modules/astro/dist/core/create-vite.js
  File:
    /home/bob/just1/juste-un-curieux/node_modules/.pnpm/astro@2.10.15_sharp@0.32.5/node_modules/astro/dist/core/create-vite.js:116:8
  Code:
    114:     envPrefix: ((_a = settings.config.vite) == null ? void 0 : _a.envPrefix) ?? "PUBLIC_",
    115:     define: {
    116:       ""https://astro-moon-landing.netlify.app/"": settings.config.site ? JSON.stringify(settings.config.site) : "und...
                 ^
    117:     },
    118:     server: {
  Stacktrace:
SyntaxError: Unexpected token (116:8) in /home/bob/just1/juste-un-curieux/node_modules/.pnpm/astro@2.10.15_sharp@0.32.5/node_modules/astro/dist/core/create-vite.js
    at pp$4.raise (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:21539:13)
    at pp$9.unexpected (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:18747:8)
    at pp$5.parsePropertyValue (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:21253:17)
    at pp$5.parseProperty (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:21198:8)
    at pp$5.parseObj (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:21153:21)
    at pp$5.parseExprAtom (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20879:17)
    at pp$5.parseExprSubscripts (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20687:19)
    at pp$5.parseMaybeUnary (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20653:17)
    at pp$5.parseExprOps (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20580:19)
    at pp$5.parseMaybeConditional (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20563:19)
    at pp$5.parseMaybeAssign (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20530:19)
    at pp$5.parsePropertyValue (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:21224:87)
    at pp$5.parseProperty (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:21198:8)
    at pp$5.parseObj (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:21153:21)
    at pp$5.parseExprAtom (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20879:17)
    at pp$5.parseExprSubscripts (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20687:19)
    at pp$5.parseMaybeUnary (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20653:17)
    at pp$5.parseExprOps (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20580:19)
    at pp$5.parseMaybeConditional (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20563:19)
    at pp$5.parseMaybeAssign (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20530:19)
    at pp$8.parseVar (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:19296:24)
    at pp$8.parseVarStatement (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:19160:8)
    at pp$8.parseStatement (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:18902:17)
    at pp$8.parseBlock (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:19229:21)
    at pp$5.parseFunctionBody (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:21358:22)
    at pp$8.parseFunction (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:19351:8)
    at pp$8.parseFunctionStatement (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:19045:15)
    at pp$8.parseStatement (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:18934:19)
    at pp$8.parseTopLevel (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:18804:21)
    at Parser.parse (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:18576:15)
    at Function.parse (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:18626:35)
    at Graph.contextParse (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:25671:38)
    at tryParse (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:7346:12)
    at analyzeTopLevelStatements (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:7365:15)
    at Object.transformAndCheckExports (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:9395:68)
    at Object.transform (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:9586:41)
    at Object.handler (file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:48270:19)
    at file:///home/bob/just1/juste-un-curieux/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:25461:40

 ELIFECYCLE  Command failed with exit code 1.

**Comment by Jean-Baptiste-Lasselle** [comment]
résolu avec la migration astro v4, et la nouvelle doc et nouvelle config astro
